# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-network-tools"
BBFILE_PATTERN_meta-network-tools = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-network-tools = "6"

LAYERDEPENDS_meta-network-tools = "core"
LAYERSERIES_COMPAT_meta-network-tools = "scarthgap"
